package com.bestmoney.cms.workflow.webscripts;

import org.alfresco.service.cmr.workflow.WorkflowService;
import org.alfresco.repo.security.authentication.AuthenticationUtil;
import org.apache.commons.lang.StringUtils;
import org.springframework.extensions.webscripts.*;

import java.util.Map;
import java.util.HashMap;

/**
 * Sign-off webscript to handle requests generated by links in
 * external sign-off email (see <code>ExternalSignOffNotification</code>)
 *
 * (Template driven webscript)
 *
 * @author martin.bergljung@opsera.com
 */
public class ExternalSignOffWebScript extends DeclarativeWebScript {
    private WorkflowService workflowService;

    public void setWorkflowService(WorkflowService workflowService) {
        this.workflowService = workflowService;
    }

    @Override
    protected Map<String, Object> executeImpl(WebScriptRequest req, Status status, Cache cache)  {
        final String id = req.getParameter("id");
        final String action = req.getParameter("action");

        if (StringUtils.isBlank(id)) {
            status.setCode(400);
            status.setMessage("'id' parameter cannot be null, empty, or blank");
        }

        if (StringUtils.isBlank(action)) {
            status.setCode(400);
            status.setMessage("'action' parameter cannot be null, empty, or blank");
        }

        Map<String, Object> model = new HashMap<String, Object>();
        model.put("response", AuthenticationUtil.runAs(
                new AuthenticationUtil.RunAsWork<String>() {
                    public String doWork() throws Exception {
                        workflowService.signal(id, action);
                        return "Success";
                    }
                }, "admin"));

        return model;
    }
}

